apiVersion: v1
data:
  common.properties: |-
    color=blue
    height=10m
  plumbing.properties: port=8080
  secret.properties: dbpassword=thisShouldProbablyBeInASecretInstead
kind: ConfigMap
metadata:
  name: prod-my-configmap-9hm8bh4gc7
